
* !!! USER MODIFIES !!! BLOCK: <BLOCK NAME> 
*EXTRACTION: RC
MILKYWAY_EXTRACT_VIEW: YES


* !!! USER MODIFIES !!! TCAD_GRD_FILE:<INSERT .nxtgrd FILEPATH>

CASE_SENSITIVE: YES
COUPLE_TO_GROUND: NO
COUPLING_MULTIPLIER: 1
POWER_EXTRACT: YES
NETLIST_FORMAT: SPF
NETLIST_NODE_SECTION: YES
NETLIST_CONNECT_SECTION: YES
NETLIST_SUBCKT: YES
NETLIST_PASSIVE_PARAMS: YES
NETLIST_TAIL_COMMENTS: YES
NETLIST_GROUND_NODE_NAME: VSS
NETLIST_MERGE_SHORTED_PORTS: YES

SHORT_PINS: NO
NETLIST_RENAME_PORTS: _

POWER_NETS: VDD VSS

NETLIST_DELIMITER: .
NETLIST_PRECISION: 6

NUM_CORES: 1
REDUCTION: NO
XREF: YES
EXTRACT_VIA_CAPS: YES
IGNORE_CAPACITANCE: NONE
KEEP_VIA_NODES: NO
MAGNIFY_DEVICE_PARAMS:NO
METAL_FILL_POLYGON_HANDLING: IGNORE
MOS_GATE_DELTA_RESISTANCE: NO
REMOVE_DANGLING_NETS: YES
REMOVE_FLOATING_NETS: YES
TRANSLATE_RETAIN_BULK_LAYERS: YES
SKIP_CELLS: !*
HIERARCHICAL_SEPARATOR: .
*OBSERVATION_POINTS: *
EXTRA_GEOMETRY_INFO: NODE

